name: Build LaTeX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ablearthy/docker-latex:1.3.0
      volumes:
        - latex_volume:/document

    steps:
      - uses: actions/checkout@v3

      - name: Build PDF
        run: latexmk -xelatex -shell-escape main.tex

      - name: Set datetime release
        run: |
          export CUR_DATE=$(date +%Y-%m-%d-%T)
          echo "CUR_DATE=$CUR_DATE" >> $GITHUB_ENV
          echo "CUR_DATE_TAG=$(echo $CUR_DATE | tr : -)" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Rename main.pdf
        run: mv main.pdf "$REPO_NAME-$CUR_DATE_TAG.pdf"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.CUR_DATE_TAG }}
          tag_name: ${{ env.CUR_DATE_TAG }}
          prerelease: true
          files: ${{ env.REPO_NAME }}-${{ env.CUR_DATE_TAG }}.pdf
        if: github.event_name != 'pull_request'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}-${{ env.CUR_DATE_TAG }}
          path: ${{ env.REPO_NAME }}-${{ env.CUR_DATE_TAG }}.pdf
        if: github.event_name == 'pull_request'